### ISSUE TITLE
Nested input types in optimistic response

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/offix#371] opened 2020-02-27 10:39 UTC
## Bug Report
The optimistic responses from mutations breakdown when the mutation resolvers require an input object rather than the fields directly. A current workaround to this is to have an optimistic response handler that unwraps the input object. This is necessary since Offix can't replace the offline generated ID if the optimistic response ID if the ID is wrapped in another object.

**Comment by wtrocki** [comment] 2020-02-28 10:19
Duplicate of https://github.com/aerogear/offix/issues/367

**Closed by wtrocki** 2020-02-28 10:19 UTC
Labels: graphback-crud
